name: "Docker build and push to Github Registry"
description: "Docker build and push to Github Registry"

inputs:
  image_name:
    description: "The image name"
    required: true
  image_tag:
    description: "The image tag"
    required: true
    default: lates
  dockerfile:
    description: "The path to the Dockerfile"
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        echo "${{ inputs.github_token }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      shell: bash
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
        IMAGE_TAG=${{ inputs.image_tag }}
        docker buildx build \
          --push \
          --tag $IMAGE_NAME:$IMAGE_TAG \
          --file ${{ inputs.dockerfile }} \
          .

    - name: Logout from GHCR
      shell: bash
      run: |
        docker logout ghcr.io
