FROM golang:1.24.5 AS build

WORKDIR /go/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY api ./api
COPY cmd/client ./cmd/client
COPY internal/client ./internal/client
COPY configs ./configs
COPY ent ./ent

RUN CGO_ENABLED=0 go build -o app ./cmd/client

FROM scratch

COPY --from=build /go/src/app/app .
COPY --from=build /go/src/app/configs ./configs
COPY --from=build /go/src/app/internal/client/web/index.html ./internal/client/web/index.html

CMD ["./app", "web"]
