services:
  robot:
    container_name: robot
    build:
      context: .
      dockerfile: Dockerfile.robot
      args:
        - TAG=${TAG}
    ports:
      - "8888:8888"
  controller:
    container_name: controller
    depends_on:
      - robot
    build:
      context: .
      dockerfile: Dockerfile.controller
      args:
        - TAG=${TAG}
    ports:
      - "5000:5000"
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - BUILDKIT_INLINE_CACHE=1
        - TAG=${TAG}
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9090/-/healthy"]
      interval: 5s
      timeout: 3s
      retries: 5
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./configs/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
