services:
  robot:
    container_name: robot
    build:
      context: .
      dockerfile: Dockerfile.robot
    ports:
      - "8888:8888"
  controller:
    container_name: controller
    depends_on:
      - robot
    build:
      context: .
      dockerfile: Dockerfile.controller
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
        - "8080:8080"
