FROM golang:1.24.5 AS build

WORKDIR /go/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY api ./api
COPY cmd/controller ./cmd/controller
COPY internal/controller ./internal/controller
COPY configs ./configs
COPY ent ./ent
COPY config.yml .

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libsqlite3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN CGO_ENABLED=1 GOOS=linux go build -o app ./cmd/controller

FROM golang:1.24.5-alpine

RUN apk add --no-cache sqlite-libs

WORKDIR /root/

COPY --from=build /go/src/app/app .
COPY --from=build /go/src/app/configs ./configs
COPY --from=build /go/src/app/config.yml ./configs/config.yml

CMD ["./app"]