name: 'GitVersion'
description: 'Set environment variables with different version options'

inputs:
  gitversion_version:
    description: 'The version of GitVersion to install'
    required: false
    default: '6.0.5'

outputs:
  semver:
    description: "The SemVer output from GitVersion"
    value: ${{ steps.gitversion.outputs.semver }}

runs:
  using: 'composite'
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '${{ inputs.gitversion_version }}'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.1
      with:
        useConfigFile: true
        configFilePath: ${{ github.action_path }}/GitVersion.yml