// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"simulator/ent/record"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecordCreate is the builder for creating a Record entity.
type RecordCreate struct {
	config
	mutation *RecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHTTPMethod sets the "http_method" field.
func (rc *RecordCreate) SetHTTPMethod(rm record.HTTPMethod) *RecordCreate {
	rc.mutation.SetHTTPMethod(rm)
	return rc
}

// SetIPAddress sets the "ip_address" field.
func (rc *RecordCreate) SetIPAddress(s string) *RecordCreate {
	rc.mutation.SetIPAddress(s)
	return rc
}

// SetInstruction sets the "instruction" field.
func (rc *RecordCreate) SetInstruction(s string) *RecordCreate {
	rc.mutation.SetInstruction(s)
	return rc
}

// SetTimestamp sets the "timestamp" field.
func (rc *RecordCreate) SetTimestamp(t time.Time) *RecordCreate {
	rc.mutation.SetTimestamp(t)
	return rc
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (rc *RecordCreate) SetNillableTimestamp(t *time.Time) *RecordCreate {
	if t != nil {
		rc.SetTimestamp(*t)
	}
	return rc
}

// Mutation returns the RecordMutation object of the builder.
func (rc *RecordCreate) Mutation() *RecordMutation {
	return rc.mutation
}

// Save creates the Record in the database.
func (rc *RecordCreate) Save(ctx context.Context) (*Record, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RecordCreate) SaveX(ctx context.Context) *Record {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RecordCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RecordCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RecordCreate) defaults() {
	if _, ok := rc.mutation.Timestamp(); !ok {
		v := record.DefaultTimestamp
		rc.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RecordCreate) check() error {
	if _, ok := rc.mutation.HTTPMethod(); !ok {
		return &ValidationError{Name: "http_method", err: errors.New(`ent: missing required field "Record.http_method"`)}
	}
	if v, ok := rc.mutation.HTTPMethod(); ok {
		if err := record.HTTPMethodValidator(v); err != nil {
			return &ValidationError{Name: "http_method", err: fmt.Errorf(`ent: validator failed for field "Record.http_method": %w`, err)}
		}
	}
	if _, ok := rc.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "Record.ip_address"`)}
	}
	if _, ok := rc.mutation.Instruction(); !ok {
		return &ValidationError{Name: "instruction", err: errors.New(`ent: missing required field "Record.instruction"`)}
	}
	if _, ok := rc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "Record.timestamp"`)}
	}
	return nil
}

func (rc *RecordCreate) sqlSave(ctx context.Context) (*Record, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *RecordCreate) createSpec() (*Record, *sqlgraph.CreateSpec) {
	var (
		_node = &Record{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(record.Table, sqlgraph.NewFieldSpec(record.FieldID, field.TypeInt))
	)
	_spec.OnConflict = rc.conflict
	if value, ok := rc.mutation.HTTPMethod(); ok {
		_spec.SetField(record.FieldHTTPMethod, field.TypeEnum, value)
		_node.HTTPMethod = value
	}
	if value, ok := rc.mutation.IPAddress(); ok {
		_spec.SetField(record.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := rc.mutation.Instruction(); ok {
		_spec.SetField(record.FieldInstruction, field.TypeString, value)
		_node.Instruction = value
	}
	if value, ok := rc.mutation.Timestamp(); ok {
		_spec.SetField(record.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Record.Create().
//		SetHTTPMethod(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecordUpsert) {
//			SetHTTPMethod(v+v).
//		}).
//		Exec(ctx)
func (rc *RecordCreate) OnConflict(opts ...sql.ConflictOption) *RecordUpsertOne {
	rc.conflict = opts
	return &RecordUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rc *RecordCreate) OnConflictColumns(columns ...string) *RecordUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RecordUpsertOne{
		create: rc,
	}
}

type (
	// RecordUpsertOne is the builder for "upsert"-ing
	//  one Record node.
	RecordUpsertOne struct {
		create *RecordCreate
	}

	// RecordUpsert is the "OnConflict" setter.
	RecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetHTTPMethod sets the "http_method" field.
func (u *RecordUpsert) SetHTTPMethod(v record.HTTPMethod) *RecordUpsert {
	u.Set(record.FieldHTTPMethod, v)
	return u
}

// UpdateHTTPMethod sets the "http_method" field to the value that was provided on create.
func (u *RecordUpsert) UpdateHTTPMethod() *RecordUpsert {
	u.SetExcluded(record.FieldHTTPMethod)
	return u
}

// SetIPAddress sets the "ip_address" field.
func (u *RecordUpsert) SetIPAddress(v string) *RecordUpsert {
	u.Set(record.FieldIPAddress, v)
	return u
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RecordUpsert) UpdateIPAddress() *RecordUpsert {
	u.SetExcluded(record.FieldIPAddress)
	return u
}

// SetInstruction sets the "instruction" field.
func (u *RecordUpsert) SetInstruction(v string) *RecordUpsert {
	u.Set(record.FieldInstruction, v)
	return u
}

// UpdateInstruction sets the "instruction" field to the value that was provided on create.
func (u *RecordUpsert) UpdateInstruction() *RecordUpsert {
	u.SetExcluded(record.FieldInstruction)
	return u
}

// SetTimestamp sets the "timestamp" field.
func (u *RecordUpsert) SetTimestamp(v time.Time) *RecordUpsert {
	u.Set(record.FieldTimestamp, v)
	return u
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *RecordUpsert) UpdateTimestamp() *RecordUpsert {
	u.SetExcluded(record.FieldTimestamp)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RecordUpsertOne) UpdateNewValues() *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Record.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RecordUpsertOne) Ignore() *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecordUpsertOne) DoNothing() *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecordCreate.OnConflict
// documentation for more info.
func (u *RecordUpsertOne) Update(set func(*RecordUpsert)) *RecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetHTTPMethod sets the "http_method" field.
func (u *RecordUpsertOne) SetHTTPMethod(v record.HTTPMethod) *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.SetHTTPMethod(v)
	})
}

// UpdateHTTPMethod sets the "http_method" field to the value that was provided on create.
func (u *RecordUpsertOne) UpdateHTTPMethod() *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateHTTPMethod()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RecordUpsertOne) SetIPAddress(v string) *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RecordUpsertOne) UpdateIPAddress() *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateIPAddress()
	})
}

// SetInstruction sets the "instruction" field.
func (u *RecordUpsertOne) SetInstruction(v string) *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.SetInstruction(v)
	})
}

// UpdateInstruction sets the "instruction" field to the value that was provided on create.
func (u *RecordUpsertOne) UpdateInstruction() *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateInstruction()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *RecordUpsertOne) SetTimestamp(v time.Time) *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *RecordUpsertOne) UpdateTimestamp() *RecordUpsertOne {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateTimestamp()
	})
}

// Exec executes the query.
func (u *RecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RecordUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RecordUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RecordCreateBulk is the builder for creating many Record entities in bulk.
type RecordCreateBulk struct {
	config
	err      error
	builders []*RecordCreate
	conflict []sql.ConflictOption
}

// Save creates the Record entities in the database.
func (rcb *RecordCreateBulk) Save(ctx context.Context) ([]*Record, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Record, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RecordCreateBulk) SaveX(ctx context.Context) []*Record {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RecordCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RecordCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Record.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RecordUpsert) {
//			SetHTTPMethod(v+v).
//		}).
//		Exec(ctx)
func (rcb *RecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *RecordUpsertBulk {
	rcb.conflict = opts
	return &RecordUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rcb *RecordCreateBulk) OnConflictColumns(columns ...string) *RecordUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RecordUpsertBulk{
		create: rcb,
	}
}

// RecordUpsertBulk is the builder for "upsert"-ing
// a bulk of Record nodes.
type RecordUpsertBulk struct {
	create *RecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RecordUpsertBulk) UpdateNewValues() *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Record.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RecordUpsertBulk) Ignore() *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RecordUpsertBulk) DoNothing() *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RecordCreateBulk.OnConflict
// documentation for more info.
func (u *RecordUpsertBulk) Update(set func(*RecordUpsert)) *RecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetHTTPMethod sets the "http_method" field.
func (u *RecordUpsertBulk) SetHTTPMethod(v record.HTTPMethod) *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.SetHTTPMethod(v)
	})
}

// UpdateHTTPMethod sets the "http_method" field to the value that was provided on create.
func (u *RecordUpsertBulk) UpdateHTTPMethod() *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateHTTPMethod()
	})
}

// SetIPAddress sets the "ip_address" field.
func (u *RecordUpsertBulk) SetIPAddress(v string) *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.SetIPAddress(v)
	})
}

// UpdateIPAddress sets the "ip_address" field to the value that was provided on create.
func (u *RecordUpsertBulk) UpdateIPAddress() *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateIPAddress()
	})
}

// SetInstruction sets the "instruction" field.
func (u *RecordUpsertBulk) SetInstruction(v string) *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.SetInstruction(v)
	})
}

// UpdateInstruction sets the "instruction" field to the value that was provided on create.
func (u *RecordUpsertBulk) UpdateInstruction() *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateInstruction()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *RecordUpsertBulk) SetTimestamp(v time.Time) *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *RecordUpsertBulk) UpdateTimestamp() *RecordUpsertBulk {
	return u.Update(func(s *RecordUpsert) {
		s.UpdateTimestamp()
	})
}

// Exec executes the query.
func (u *RecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
