// Code generated by ent, DO NOT EDIT.

package ent

import (
	"simulator/ent/record"
	"simulator/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	recordFields := schema.Record{}.Fields()
	_ = recordFields
	// recordDescTimestamp is the schema descriptor for timestamp field.
	recordDescTimestamp := recordFields[3].Descriptor()
	// record.DefaultTimestamp holds the default value on creation for the timestamp field.
	record.DefaultTimestamp = recordDescTimestamp.Default.(time.Time)
}
