name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Test
      run: go test ./...

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        TAG=""
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          TAG="latest"
        elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
          TAG="development"
        else
          TAG="alpha-${{ github.sha }}"
        fi
        make build TAG=$TAG
