name: Build and Push Client

on:
  push:
    branches:
      - main
    # paths:
    #   - 'cmd/client/**'
    #   - 'internal/client/**'
    #   - 'go.mod'
    #   - 'go.sum'

jobs:
  build:
    permissions:
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    with:
      dockerfile: Dockerfile.client
      image_name: simulator-client
    secrets: inherit
