name: Build and Push Controller

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/controller/**'
      - 'internal/controller/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/build-and-push.yml
    with:
      dockerfile: Dockerfile.controller
      image_name: simulator-controller
    secrets: inherit